# @generated by https://codeberg.org/goldstein/unflake
let
  deps = rec {
    unflake_github_nix-community_home-manager = builtins.fetchTree {
      type = "github";
      owner = "nix-community";
      repo = "home-manager";
      rev = "e4e78a2cbeaddd07ab7238971b16468cc1d14daf";
      lastModified = 1767104570;
      narHash = "sha256-GKgwu5//R+cLdKysZjGqvUEEOGXXLdt93sNXeb2M/Lk=";
    };
    unflake_github_nix-systems_default = builtins.fetchTree {
      type = "github";
      owner = "nix-systems";
      repo = "default";
      rev = "da67096a3b9bf56a91d16901293e51ba5b49a27e";
      lastModified = 1681028828;
      narHash = "sha256-Vy1rq5AaRuLzOxct8nz4T6wlgyUR7zLU309k9mBC768=";
    };
    unflake_github_nixos_nixpkgs_ref_nixos-unstable = builtins.fetchTree {
      type = "github";
      owner = "nixos";
      repo = "nixpkgs";
      rev = "cad22e7d996aea55ecab064e84834289143e44a0";
      lastModified = 1767116409;
      narHash = "sha256-5vKw92l1GyTnjoLzEagJy5V5mDFck72LiQWZSOnSicw=";
    };
    unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable = builtins.fetchTree {
      type = "github";
      owner = "nixos";
      repo = "nixpkgs";
      rev = "c04833a1e584401bb63c1a63ddc51a71e6aa457a";
      lastModified = 1767242400;
      narHash = "sha256-knFaYjeg7swqG1dljj1hOxfg39zrIy8pfGuicjm9s+o=";
    };
    unflake_github_numtide_flake-utils = builtins.fetchTree {
      type = "github";
      owner = "numtide";
      repo = "flake-utils";
      rev = "11707dc2f618dd54ca8739b309ec4fc024de578b";
      lastModified = 1731533236;
      narHash = "sha256-l0KFg5HjrsfsO/JpG+r7fRrqm12kzFHyUHqHCVpMMbI=";
    };
    unflake_tarball_https---codeberg-org-goldstein-unflake-archive-main-tar-gz = builtins.fetchTree {
      type = "tarball";
      url = "https://codeberg.org/api/v1/repos/goldstein/unflake/archive/553a30b7cd24e67aa0335a6ecf0dfd18a5224cb5.tar.gz";
      lastModified = 1766770453;
      narHash = "sha256-dc+eHCfndHdhObhQTEHax3Qu4Ouy++2azvVusiruOiY=";
    };
  };
  universe = rec {
    unflake_github_nix-community_home-manager = ((import "${deps.unflake_github_nix-community_home-manager.outPath}/flake.nix").outputs {
      self = unflake_github_nix-community_home-manager;
      nixpkgs = unflake_github_nixos_nixpkgs_ref_nixos-unstable;
    }) // deps.unflake_github_nix-community_home-manager // {
      _flake = true;
      outPath = "${deps.unflake_github_nix-community_home-manager.outPath}";
      sourceInfo = deps.unflake_github_nix-community_home-manager;
    };
    unflake_github_nix-systems_default = ((import "${deps.unflake_github_nix-systems_default.outPath}/flake.nix").outputs {
      self = unflake_github_nix-systems_default;
    }) // deps.unflake_github_nix-systems_default // {
      _flake = true;
      outPath = "${deps.unflake_github_nix-systems_default.outPath}";
      sourceInfo = deps.unflake_github_nix-systems_default;
    };
    unflake_github_nixos_nixpkgs_ref_nixos-unstable = ((import "${deps.unflake_github_nixos_nixpkgs_ref_nixos-unstable.outPath}/flake.nix").outputs {
      self = unflake_github_nixos_nixpkgs_ref_nixos-unstable;
    }) // deps.unflake_github_nixos_nixpkgs_ref_nixos-unstable // {
      _flake = true;
      outPath = "${deps.unflake_github_nixos_nixpkgs_ref_nixos-unstable.outPath}";
      sourceInfo = deps.unflake_github_nixos_nixpkgs_ref_nixos-unstable;
    };
    unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable = ((import "${deps.unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable.outPath}/flake.nix").outputs {
      self = unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable;
    }) // deps.unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable // {
      _flake = true;
      outPath = "${deps.unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable.outPath}";
      sourceInfo = deps.unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable;
    };
    unflake_github_numtide_flake-utils = ((import "${deps.unflake_github_numtide_flake-utils.outPath}/flake.nix").outputs {
      self = unflake_github_numtide_flake-utils;
      systems = unflake_github_nix-systems_default;
    }) // deps.unflake_github_numtide_flake-utils // {
      _flake = true;
      outPath = "${deps.unflake_github_numtide_flake-utils.outPath}";
      sourceInfo = deps.unflake_github_numtide_flake-utils;
    };
    unflake_tarball_https---codeberg-org-goldstein-unflake-archive-main-tar-gz = ((import "${deps.unflake_tarball_https---codeberg-org-goldstein-unflake-archive-main-tar-gz.outPath}/flake.nix").outputs {
      self = unflake_tarball_https---codeberg-org-goldstein-unflake-archive-main-tar-gz;
      nixpkgs = unflake_github_nixos_nixpkgs_ref_nixos-unstable;
    }) // deps.unflake_tarball_https---codeberg-org-goldstein-unflake-archive-main-tar-gz // {
      _flake = true;
      outPath = "${deps.unflake_tarball_https---codeberg-org-goldstein-unflake-archive-main-tar-gz.outPath}";
      sourceInfo = deps.unflake_tarball_https---codeberg-org-goldstein-unflake-archive-main-tar-gz;
    };
  };
  inputs = {
    flake-utils = universe.unflake_github_numtide_flake-utils;
    home-manager = universe.unflake_github_nix-community_home-manager;
    nixpkgs = universe.unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable;
    unflake = universe.unflake_tarball_https---codeberg-org-goldstein-unflake-archive-main-tar-gz;
    self = throw "to use inputs.self, write `import ./unflake.nix (inputs: ...)`";
    withInputs = outputs: let self = outputs (inputs // { inherit self; }); in self;
    __functor = self: self.withInputs;
  };
in inputs